[package]
name = "storage-hal"
version = "2.0.0"
edition = "2021"

[dependencies]
reed-solomon-erasure = "4.0"
blake3 = "1.5"
tonic = "0.10"
prost = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.10"