name: Android App CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/android/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Placeholder
        run: echo "Building Android app..."